### ISSUE TITLE
[FEATURE REQUEST] Widget 

### ISSUE THREAD

**Issue by HarriBuh** [v4lpt/ETW#1]
Hi there, I started using your app yesterday and while really endorsing the concept, I miss the practical feature of a permanent, visual reminder on my home screen, just like a widget would do.

Can you add it?

Cheers.

**Comment by v4lpt** [comment]
progress so far: 
![image](https://github.com/user-attachments/assets/12e928ec-4473-44e5-9ce5-6b6ccec7ab48)

it's going well. 
Progress:
- [x] make the widget update
- [x] use androids alarm feature so that the app doesn't have to run in the background
- [x] make the image show up in the widget 
- [x] create an event picker for picking an event for the widget 
- [x] make the widget resizable, 3x1, 4x1 or 5x1 
- [ ] make the text have the outline (not possible with my approach right now, optional)
- [ ] make it not crash if the image is a bit large (possibly by using glide's override feature or not rendering it as a bitmap) 
- [ ] make the preview pretty

**Comment by HarriBuh** [comment]
Would there be fewer problems if you didn't put the individual picture inside that widget? I don't think it's really needed anyway.

**Comment by v4lpt** [comment]
Widget support has been added, check out the new release!
https://github.com/v4lpt/ETW/releases/tag/v1.1.0

if there are migration issues let me know

**Comment by v4lpt** [comment]
you can add a 3x1, 4x1 and 5x1 widget :)

**Comment by v4lpt** [comment]
Info: you have to manually delete and re-add old events to save them as widgets
